on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
        types: [ "review_requested", "ready_for_review" ]
    workflow_dispatch:
name: CI
permissions:
    id-token: write
    contents: read
jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                dotnet-version: [ '9.0.x' ]
        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: ${{ matrix.dotnet-version }}
            - name: Install dependencies
              run: dotnet restore Nickvision.FlatpakGenerator/Nickvision.FlatpakGenerator.csproj
            - name: Build
              run: dotnet build Nickvision.FlatpakGenerator/Nickvision.FlatpakGenerator.csproj --configuration Release --no-restore
            - name: Pack
              run: dotnet pack Nickvision.FlatpakGenerator/Nickvision.FlatpakGenerator.csproj --output ${{github.workspace}}/nuget
            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                  path: ${{github.workspace}}/nuget
                  name: Nuget
